<a href="https://colab.research.google.com/github/SH0312/KOSA_Pytorch/blob/main/1_linear.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch

In [ ]:
x = torch.randn(2,3)

In [ ]:
y = torch.rand(2,3)

In [ ]:
a = x.to('cuda')

In [ ]:
#python

In [ ]:
# Y = Wx + b
# input: 10 Ouput: 5 Linear Transform

In [1]:
import torch
from torch.autograd import Variable
from torch.nn import Linear

data = Variable(torch.randn(1, 10))
Layer =Linear(in_features=10, out_features=5, bias=True)

In [ ]:
Layer(data)

tensor([[-0.3379, -0.2850,  0.0090, -1.1616,  0.5723]],
       grad_fn=<AddmmBackward>)

In [3]:
data

tensor([[-1.4285,  0.2805,  0.3254, -0.7319,  0.3147, -0.7350,  1.8184,  1.2629,
          0.4362, -0.7057]])

In [4]:
Layer(data)

tensor([[-0.2786,  0.0247, -0.0538,  0.4510, -0.6686]],
       grad_fn=<AddmmBackward>)

In [7]:
Layer.weight

Parameter containing:
tensor([[-0.0958, -0.1483, -0.0450, -0.1528,  0.0669, -0.0609, -0.0558, -0.0400,
         -0.2650, -0.0014],
        [-0.2506, -0.2482, -0.1058,  0.1487,  0.0669, -0.0483, -0.0421,  0.2015,
         -0.1688,  0.0197],
        [-0.2285, -0.1545, -0.0035, -0.1038, -0.0812,  0.1212, -0.2745, -0.1630,
         -0.0485, -0.2406],
        [-0.1008,  0.2040,  0.1836, -0.0575,  0.1986, -0.1681, -0.2033,  0.1723,
          0.0814,  0.1285],
        [ 0.2380,  0.0220,  0.1136, -0.2193,  0.2978,  0.2691, -0.3061,  0.1960,
         -0.3112,  0.1902]], requires_grad=True)

In [8]:
Layer.bias

Parameter containing:
tensor([-0.2703, -0.2672,  0.2592,  0.1693,  0.1508], requires_grad=True)

In [ ]:
# Activation Function -> ReLu

In [10]:
from torch.nn import ReLU
import torch

In [13]:
data = torch.Tensor([[3, 1, 2, -1, -2, -3]])

In [14]:
relu = ReLU()
relu(data)

tensor([[3., 1., 2., 0., 0., 0.]])

In [ ]:
# Feedforward & Back Propagation
# https://blog.naver.com/slykid/222007253786

In [1]:
import torch
from torch import nn
from torch.autograd import Variable

In [2]:
class Network_ex(nn.Module):
    def __init__(self, input_size, hidden_size, output_size):
        super(Network_ex).__init__()
        self.layer1 = nn.Linear(input_size, hidden_size)
        self.layer2 = nn.Linear(hidden_size, output_size)
        
    def forward(self, input):
        out = self.Layer1(input)
        out = nn.ReLU(out)
        out = self.layer2(out)
        
        return out

In [3]:
loss = nn.MSELoss()
data = Variable(torch.randn(3, 5), requires_grad=True)

In [4]:
data

tensor([[ 0.2352,  1.8564, -1.0107,  0.3438, -1.1640],
        [ 0.2514,  0.1252, -0.7098,  0.4094,  0.2047],
        [ 1.6260,  1.5588,  0.7945, -0.8594, -0.8660]], requires_grad=True)

In [5]:
target = Variable(torch.randn(3, 5))

In [6]:
target

tensor([[ 7.2081e-01,  7.9161e-01,  1.1303e+00, -1.9952e+00,  2.7820e-01],
        [ 1.1221e+00,  4.9422e-01, -1.5115e-03,  1.0903e-01,  9.6144e-01],
        [ 5.7931e-02, -1.8966e+00, -3.7742e-01,  1.0982e-01,  1.4630e+00]])

In [11]:
output = loss(data, target)
output.backward()

In [13]:
output

tensor(2.5133, grad_fn=<MseLossBackward>)

In [14]:
data

tensor([[ 0.2352,  1.8564, -1.0107,  0.3438, -1.1640],
        [ 0.2514,  0.1252, -0.7098,  0.4094,  0.2047],
        [ 1.6260,  1.5588,  0.7945, -0.8594, -0.8660]], requires_grad=True)